### ISSUE TITLE
👎 

### ISSUE THREAD

**Issue by henry-lin2** [CSY1063/as1-jay-toon#11]
-100 SOCIAL CREDITS
🇨🇳 🇨🇳 🇨🇳 🐻 🇨🇳 🇨🇳 🇨🇳

**Comment by jay-toon** [comment]
请使用微信联系我，以便我们进一步讨论。我热爱中国，所以我永远不会失去我的社会信用。

谢谢你，我希望能有一次愉快的交谈。
