### ISSUE TITLE
🧑‍⚖️ 

### ISSUE THREAD

**Issue by henry-lin2** [CSY1063/as1-jay-toon#19]
We are hear today to listen to the courts verdict on the subject Jay Toon. 
Did Jay Toon fail the AS1 portfolio website assignment? We, the court, found him guilty.
Did Jay Toon use an absolute URL? We, the court, found him guilty.
We, the court, found him guilty on all accounts.

He will be receiving a 84 years in prison.

**Comment by jay-toon** [comment]
我想重新开庭并起诉法院使用不合格的律师和陪审团造成的重大不公正。
