### ISSUE TITLE
Greetings Jay Toon

### ISSUE THREAD

**Issue by henry-lin2** [CSY1063/as1-jay-toon#2]
Hello Jay, regarding your portfolio website. 
It unfortunately doesn't work. NOT VERY COOL.

**Comment by henry-lin2** [comment]
Hi Jay Toon. Please RESPOND as soon as you can. You have a large amount of time to respond. However, it would be quite uncool for you to ignore my important comments as they will benefit you greatly.

**Comment by jay-toon** [comment]
No GPU, No Speed. Ratio.

**Comment by monsterkane05** [comment]
It appears that you have used a slash at the start of your links. This has made the site inoperable please follow the regulations outlined by W3C [https://www.w3.org/standards/about/]. This will help you get your site back displaying correctly.

**Comment by jay-toon** [comment]
Thank you for informing me of this tragic bug. My front-end development team at r*****.tech have been informed of this error, and we will get back and let you know when it is completed. Any more issues, please follow up!

Kind regards,
Jay Toon
Dictator of NuSoft PLC

**Comment by jay-toon** [comment]
Hello @monsterkane05!

Our front-end development team have fixed the issue at hand. Any more issues, please let us know!
Thank you for your cooperation during this open source web development project.

Thanks again,
Jay Toon
Dictator of NuSoft PLC

**Comment by monsterkane05** [comment]
Good Afternoon, @jay-toon 

This appears to have fixed the issues at hand. Send my regards to the front-end development team.

Thanks again,
Kane Partridge
International technology coordination and management officer - NuSoft PLC

**Comment by jay-toon** [comment]
Thank you, kind sir.

Send my regards to the International Technology Coordination and Management Office at NuSoft PLC!

Kind regards,
Jay Toon
Dictator at NuSoft PLC
