### ISSUE TITLE
👨‍🏫 "DO YOUR WORK"

### ISSUE THREAD

**Issue by henry-lin2** [CSY1063/as1-jay-toon#22]
[Work 1.pdf](https://github.com/CSY1063/as1-jay-toon/files/14652692/Work.1.pdf)
[Work 2.pdf](https://github.com/CSY1063/as1-jay-toon/files/14652693/Work.2.pdf)

**Comment by henry-lin2** [comment]
Submit your answers below 😄

**Comment by jay-toon** [comment]
[answers1.pdf](https://github.com/CSY1063/as1-jay-toon/files/14652976/answers1.pdf)
[answers2.pdf](https://github.com/CSY1063/as1-jay-toon/files/14652975/answers2.pdf)

**Comment by jay-toon** [comment]
Please let me know how I performed!
