### ISSUE TITLE
📰 

### ISSUE THREAD

**Issue by henry-lin2** [CSY1063/as1-jay-toon#23]
![Jay](https://github.com/CSY1063/as1-jay-toon/assets/159941663/6905b79f-d3b1-4af0-8528-ac0bf1d400f1)
JAY TOON FREE FROM PRISON!

**Comment by jay-toon** [comment]
我绝对不会纵容包括你在内的坏人。你给你的家人带来了极大的失望和缺乏荣誉。你是一个失败的人。
